{"name": "Проверка авторизации - неправильно указан пароль", "status": "failed", "statusDetails": {"message": "AssertionError: assert (500 == 404)\n +  where 500 = <Response [500]>.status_code", "trace": "self = <test_login.TestLogin object at 0x000001E528EBED50>\n\n    @allure.title('Проверка авторизации - неправильно указан пароль')\n    def test_login_wrong_password(self):\n        payload = {\"login\": \"Art88\", \"password\": \"555444\"}\n        response = requests.post(urls.BASE_URL + urls.LOGIN_ENDPOINT, json=payload)\n>       assert response.status_code == 404 and response.json() == {\"code\": 404, \"message\": \"Учетная запись не найдена\"}\nE       assert (500 == 404)\nE        +  where 500 = <Response [500]>.status_code\n\ntests\\test_login.py:16: AssertionError"}, "start": 1742311362629, "stop": 1742311363349, "uuid": "3f6f9975-ff6c-4103-90bc-087768f89e25", "historyId": "6145621d0931d5253f5720f2553e41dc", "testCaseId": "6145621d0931d5253f5720f2553e41dc", "fullName": "tests.test_login.TestLogin#test_login_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-GGM4SCM"}, {"name": "thread", "value": "8780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}